[project]
name = "scheduler"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "iesopt>=2.8.0",
    "pandas>=2.3.1",
]

[tool.ruff]
line-length = 120
target-version = "py312"
